/**
 * Golden-file lock: the emitters must reproduce fixtures/ byte-for-byte.
 * When an emitter change is intentional, run `bun run fixtures` and review
 * the fixture diff in the commit — that diff IS the emitter's changelog.
 */

import { describe, expect, it } from "bun:test";
import { readdirSync, readFileSync } from "node:fs";
import { buildFixtures } from "../scripts/gen-fixtures.tsx";

const dir = new URL("../fixtures/", import.meta.url);

describe("fixtures are the emitters' canonical output", () => {
  const fixtures = buildFixtures();

  for (const [name, content] of Object.entries(fixtures)) {
    it(`fixtures/${name} matches the emitter byte-for-byte`, () => {
      const onDisk = readFileSync(new URL(name, dir), "utf8");
      expect(onDisk).toBe(content);
    });
  }

  it("no stale fixture files", () => {
    const expected = new Set(Object.keys(buildFixtures()));
    // Emitter fixtures are flat files. The fixtures/pdf/ subdirectory is a
    // separate fixture family (the frozen ParseBench sample + layout + oracle,
    // regenerated by `bun run fixtures:pdf` via scripts/pdf/build-fixture.tsx —
    // see PDF-PIPELINE.md), not emitter output, so this emitter-scoped check
    // ignores subdirectories.
    const actual = readdirSync(dir, { withFileTypes: true })
      .filter((e) => e.isFile() && !e.name.startsWith("README"))
      .map((e) => e.name);
    expect(actual.sort()).toEqual([...expected].sort());
  });
});
