/**
 * THE flue compat proof: the generated modules must satisfy the REAL
 * @flue/runtime (linked from ~/dev/flue). Flue's own validators are the
 * oracle — defineAgent/defineAgentProfile throw on invalid shapes, so a
 * clean import IS the assertion. If flue's actual API differs from what the
 * emitters guessed (likely!), fix the EMITTERS to match flue — never stub
 * or mock @flue/runtime, and never weaken these assertions.
 *
 * If @flue/runtime needs building first, build it in the flue checkout
 * (read-only otherwise): pnpm install + the repo's build task.
 */

import { describe, expect, it } from "vitest";
// Generated by scripts/generate.ts:
import uptimeAgent, { spawnPlan } from "../src/generated/uptime.flue.ts";
import { investigatorProfile } from "../src/generated/investigator.flue.ts";
import { tool_workerProfile } from "../src/generated/tool-worker.flue.ts";
import coordinatorAgent from "../src/generated/coordinator.flue.ts";

const incident = {
  statuses: { "https://b.example": { state: "down" as const, since: 4 } },
  findings: {},
};

describe("generated modules against real @flue/runtime", () => {
  it("parent module passes flue's defineAgent validation on import", () => {
    expect(uptimeAgent).toBeTruthy();
  });

  it("parent config declares generated child profiles for session.task lookup", async () => {
    const config = await (
      uptimeAgent as { initialize: (ctx: unknown) => Promise<{ subagents?: { name?: string }[] }> }
    ).initialize({});
    expect(config.subagents?.map((s) => s.name)).toContain("investigator");
  });

  it("child profile passes flue's profile validation and carries the prompt", () => {
    expect(investigatorProfile).toBeTruthy();
    const serialized = JSON.stringify(investigatorProfile);
    expect(serialized).toContain("investigator");
    expect(serialized).toContain("You investigate ONE outage");
  });

  it("a schema-driven child profile carries description through real flue validation", () => {
    // Clean import already ran flue's defineAgentProfile validator (the oracle);
    // the emitted spec.description survives it as a first-class profile field.
    expect(tool_workerProfile).toBeTruthy();
    expect((tool_workerProfile as { description?: string }).description).toBe(
      "Answer a research query from the document corpus."
    );
  });

  it("aliases a tool-slot child by the explicit prop key in the real Flue roster", async () => {
    const config = await (
      coordinatorAgent as { initialize: (ctx: unknown) => Promise<{ subagents?: { name?: string }[] }> }
    ).initialize({});
    expect(config.subagents?.map((profile) => profile.name)).toEqual(["onCall"]);
  });

  it("spawnPlan derives stable-id descriptors from state", () => {
    const plan = spawnPlan(incident);
    expect(plan).toHaveLength(1);
    expect(plan[0]).toMatchObject({
      stableId: "investigate:https://b.example",
      agent: "investigator",
    });
    expect((plan[0] as unknown as { input: { site: string } }).input.site).toBe("https://b.example");
  });

  it("spawnPlan is empty at rest (dynamic residue only exists under incident)", () => {
    expect(spawnPlan({ statuses: {}, findings: {} })).toHaveLength(0);
  });
});
