/**
 * v0.5 flue compat — the generated WORKFLOW module against the real
 * @flue/runtime (RED until scripts/generate.tsx emits it and the emitter
 * exists).
 *
 * Oracles, strongest available first:
 *   1. Module load: flue's defineWorkflow validates at call time (input
 *      schema top-level v.object rule) — a clean import is an assertion.
 *      Strengthen with flue's own workflow type guard if exported
 *      (mirror isAgentDefinition in packages/runtime/src/agent-definition.ts);
 *      cite the source when adjusting.
 *   2. Execution: run the workflow body end-to-end. Prefer flue's real
 *      harness via @flue/runtime/test-utils if it can run headless with a
 *      scripted model; otherwise drive run() with a minimal fake harness
 *      whose session.task returns deterministic results — the fake mirrors
 *      the REAL session.task(prompt, { agent }) shape (cite flue source) and
 *      only the transport is faked, never @flue/runtime itself.
 *
 * Behavior that may not be weakened: importing validates; executing from an
 * incident state delegates exactly ["investigate:https://b.example"] to the
 * "investigator" agent and returns final state whose findings contain the
 * task result; resting state delegates nothing.
 */

import { describe, expect, it } from "vitest";
// Generated by scripts/generate.tsx (v0.5):
import workflow from "../src/generated/uptime.workflow.ts";

const incident = {
  statuses: { "https://b.example": { state: "down" as const, since: 4 } },
  findings: {},
};

describe("generated workflow against real @flue/runtime", () => {
  it("module loads and is a flue workflow definition", () => {
    expect(workflow).toBeTruthy();
    // FACTUAL API SHAPE (not a weakening — a strengthening): real defineWorkflow
    // returns a frozen { __flueWorkflowDefinition, agent, action } and folds
    // run() into `action` via defineAction — there is no top-level `.run`
    // (workflow-definition.ts:52-105; action.ts:29-39, :93-100). A clean import
    // already passed flue's load-time validation (isAgentDefinition on `agent`,
    // top-level-object check on `input`); these assert the returned shape.
    expect((workflow as { __flueWorkflowDefinition?: unknown }).__flueWorkflowDefinition).toBe(true);
    expect(typeof (workflow as { action?: { run?: unknown } }).action?.run).toBe("function");
  });

  it("executes the reactive loop: delegates the incident child and folds the result back", async () => {
    const delegations: { prompt: string; agent: string }[] = [];
    // Fake ONLY the transport, never @flue/runtime. This mirrors the REAL shape:
    //   harness.session() → Promise<FlueSession>            (types.ts:462-469)
    //   session.task(text, { agent }) → { text, ... }       (types.ts:552-556 task,
    //   :674-683 TaskOptions.agent, :620-627 PromptResponse.text)
    const fakeHarness = {
      session: async () => ({
        task: async (prompt: string, opts: { agent: string }) => {
          delegations.push({ prompt, agent: opts.agent });
          return { text: `investigated by ${opts.agent}` };
        },
      }),
    };

    // run() lives on `action` (see the shape assertion above); the runtime calls
    // action.run(ActionContext) with { harness, log, input } (action.ts:126-147).
    const result = (await (
      workflow as { action: { run: (ctx: unknown) => Promise<unknown> } }
    ).action.run({
      harness: fakeHarness,
      input: { state: incident },
    })) as { state: { findings: Record<string, string> }; delegated: string[] };

    expect(result.delegated).toEqual(["investigate:https://b.example"]);
    expect(delegations).toHaveLength(1);
    expect(delegations[0]!.agent).toBe("investigator");
    expect(Object.values(result.state.findings).join(" ")).toContain("investigated by investigator");
  });

  it("delegates nothing from the resting state", async () => {
    const fakeHarness = {
      session: async () => ({
        task: async () => {
          throw new Error("must not delegate at rest");
        },
      }),
    };
    const result = (await (
      workflow as { action: { run: (ctx: unknown) => Promise<unknown> } }
    ).action.run({
      harness: fakeHarness,
      input: { state: { statuses: {}, findings: {} } },
    })) as { delegated: string[] };
    expect(result.delegated).toEqual([]);
  });
});
