/**
 * Compiler-owned lowering for authored agent sources. Two modes:
 *
 * - CLASS: one hierarchy-free, Cloudflare-style agent class. The authored file
 *   owns state, one rendered model/prompt/tools/skills/MCP definition, and
 *   @callable methods; the companion turns it into a composable JSX boundary
 *   through compileAgentClass.
 * - FUNCTION: one PascalCase function component plus an explicit `profile`
 *   export (defineAgentProfile). The companion lowers it through compileAgent
 *   and re-exports the boundary under the SAME public JSX name.
 *
 * Parent/child relationships remain exclusively in composition JSX.
 */

export interface AgentModuleEmitOptions {
  /** Import path from the generated companion to the authored *.agent.tsx. */
  sourceImport: string;
  /** Public generated component export, e.g. OpenAIAgent. */
  exportName: string;
  /** Import path from the companion to the lowering runtime module
   *  (agent-class.tsx for class mode, agent-component.tsx for function mode). */
  runtimeImport?: string;
  /** Authored source kind. Default "class". */
  mode?: "class" | "function";
  /** Named profile export on the authored module (function mode). */
  profileExport?: string;
}

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

function assertIdentifier(value: string, label: string): void {
  if (!IDENTIFIER.test(value)) {
    throw new Error(`[agent-jsx] ${label} must be a JavaScript identifier; received ${JSON.stringify(value)}`);
  }
}

/** Emit the tiny boundary companion consumed by composition and target emitters. */
export function emitAgentModule(options: AgentModuleEmitOptions): string {
  const mode = options.mode ?? "class";
  const runtimeImport =
    options.runtimeImport ??
    (mode === "function"
      ? "@agent-jsx/core/agent-component"
      : "@agent-jsx/core/agent");
  assertIdentifier(options.exportName, "exportName");

  if (mode === "function") {
    const profileExport = options.profileExport ?? "profile";
    assertIdentifier(profileExport, "profileExport");
    return `// GENERATED by agent-jsx from ${options.sourceImport}. Do not edit.
// Function-to-boundary lowering is compiler-owned; hierarchy lives in composition JSX.

import AgentImplementation, { ${profileExport} as agentProfile } from ${JSON.stringify(options.sourceImport)};
import { compileAgent } from ${JSON.stringify(runtimeImport)};

export const ${options.exportName} = compileAgent(
  AgentImplementation,
  agentProfile,
);

export default ${options.exportName};
`;
  }

  return `// GENERATED by agent-jsx from ${options.sourceImport}. Do not edit.
// Class-to-boundary lowering is compiler-owned; hierarchy lives in composition JSX.

import AgentDefinition from ${JSON.stringify(options.sourceImport)};
import { compileAgentClass } from ${JSON.stringify(runtimeImport)};

export const ${options.exportName} = compileAgentClass(AgentDefinition);

export default ${options.exportName};
`;
}
