/**
 * Source-file lowering for the author-facing agent format.
 *
 * Authored `*.agent.tsx` files export two ordinary values:
 *   - a default pure JSX function (the agent implementation), and
 *   - `profile`, created with defineAgentProfile (metadata + explicit ACL).
 *
 * This emitter owns the agentComponent ceremony. The generated companion is
 * what composition code and target emitters import, so a source component is
 * never accidentally evaluated inline across an agent boundary.
 */

export interface AgentModuleEmitOptions {
  /** Import path from the generated companion to the authored *.agent.tsx. */
  sourceImport: string;
  /** Public generated component export, e.g. OpenAIAgent. */
  exportName: string;
  /** Named profile export in the source module. */
  profileExport?: string;
  /** Import path from the companion to agent-component.tsx. */
  runtimeImport?: string;
}

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

function assertIdentifier(value: string, label: string): void {
  if (!IDENTIFIER.test(value)) {
    throw new Error(`[agent-jsx] ${label} must be a JavaScript identifier; received ${JSON.stringify(value)}`);
  }
}

/** Emit the tiny boundary companion consumed by the rest of the compiler. */
export function emitAgentModule(options: AgentModuleEmitOptions): string {
  const profileExport = options.profileExport ?? "profile";
  const runtimeImport = options.runtimeImport ?? "agent-jsx/agent-component";
  assertIdentifier(options.exportName, "exportName");
  assertIdentifier(profileExport, "profileExport");

  return `// GENERATED by agent-jsx from ${options.sourceImport}. Do not edit.
// agentComponent and capability normalization are compiler-owned lowering.

import AgentImplementation, { ${profileExport} as agentProfile } from ${JSON.stringify(options.sourceImport)};
import { compileAgent } from ${JSON.stringify(runtimeImport)};

export const ${options.exportName} = compileAgent(
  AgentImplementation,
  agentProfile,
);

export default ${options.exportName};
`;
}
