/**
 * Compile target #1: cloudflare/agents — MULTI-AGENT.
 *
 * You write agent component files; this emitter generates the composition
 * glue the runtime otherwise makes you hand-write:
 *
 *   - one `Agent` subclass per agent component (parent AND children),
 *     sharing a generated FiberAgentBase (evaluate → diff → apply);
 *   - typed `this.subagent(kind, name)` accessors over getAgentByName;
 *   - props ACROSS the actor boundary: parent re-render diffs a child's
 *     serializable props → generated `setProps` RPC → child re-renders;
 *   - callbacks ACROSS the boundary: `onResult={fn}` compiles to a
 *     CallbackRef; the child's impl receives a proxy that RPCs the parent's
 *     generated `onAgentEvent` dispatcher, which routes to the freshest
 *     closure from the parent's latest render;
 *   - the wrangler fragment: DO bindings + migrations for every class
 *     (the ceremony flue's DO-naming gotchas made painful).
 *
 * No React ships: components are evaluated by the ~70-line walker, and the
 * runtime closure (evaluate/collect/prompt/store) is the react-free file set
 * copied to `emitRuntimeTo`. See COMPAT-REPORT.md for the real-workerd API
 * divergences this template encodes (this.ctx.id vs this.name, onStateChanged,
 * setState-bridged store, structured callback payloads).
 */

import type { AgentSpec } from "../agent-component.tsx";
import type { Analysis } from "./analyze.ts";
import { emitRuntimeFiles } from "./runtime-files.ts";
import { evaluateComponent } from "./evaluate.ts";
import { collectInfra } from "../tree.ts";
import { createStore } from "../store.ts";

export interface RootAgentSpec {
  /** The root agent's spec — the SAME `agentComponent(spec)` children use. The
   *  emitter consumes ONLY this: agentName (class/binding), initialState
   *  (embedded as JSON), sampleProps (root props), impl (renderTree), and the
   *  optional getPrompt seam. No stringly stateTypeName/initialStateExport/
   *  propsJson plumbing. */
  spec: AgentSpec;
  /** Export name + import path of the agentComponent — the generated module
   *  imports it for renderTree (`.spec.impl`) and structural state typing
   *  (`typeof ComponentName.spec.initialState`). */
  componentName: string;
  componentImport: string;
  /** Optional Cloudflare Agent onRequest handler generated by another emitter. */
  requestHandlerExport?: string;
  requestHandlerImport?: string;
}

export interface ChildAgentSpec {
  spec: AgentSpec;
  /** e.g. `Investigator` — the agentComponent export. */
  exportName: string;
  importPath: string;
}

export interface EmitOptions {
  /** Rewrites the generated runtime imports off `../../src` (e.g. "./runtime"). */
  runtimeImport?: string;
  /** Absolute fs path; when set, the react-free runtime file set is copied here. */
  emitRuntimeTo?: string;
  /** Seconds per component tick: `interval`/`every` are authored in sim ticks;
   *  a deployed agent multiplies them into wall-clock seconds. Default 1. */
  intervalScale?: number;
}

export interface CloudflareEmit {
  agents: string; // the generated module
  wrangler: string; // wrangler.jsonc fragment
}

const pascal = (s: string) => s.replace(/(?:^|[-_:])(\w)/g, (_, c) => c.toUpperCase());
const scream = (s: string) => s.replace(/[-:]/g, "_").toUpperCase();

/** Distinct subagent kinds an analysis reveals — the agentNames this agent
 *  directly nests (static, dynamic, or both). Preserves first-seen order. */
function subagentKindsFromAnalysis(analysis: Analysis): string[] {
  const kinds: string[] = [];
  for (const r of [...analysis.static, ...analysis.dynamic]) {
    if (r.kind === "subagent") {
      const k = String(r.config.kind);
      if (!kinds.includes(k)) kinds.push(k);
    }
  }
  return kinds;
}

/** Distinct subagent kinds a component's OWN render reveals — its direct nested
 *  boundaries — by evaluating the impl at sampleProps + initialState. The
 *  always-on boundaries surface every nested kind (dynamic fan-out only
 *  multiplies instances of a kind already present). */
function childKindsOfSpec(spec: AgentSpec): string[] {
  const kinds: string[] = [];
  const roots = evaluateComponent(spec.impl, {
    ...(spec.sampleProps ?? {}),
    store: createStore(spec.initialState),
  } as never);
  for (const root of roots) {
    for (const rec of collectInfra(root)) {
      if (rec.kind === "subagent") {
        const k = String(rec.config.kind);
        if (!kinds.includes(k)) kinds.push(k);
      }
    }
  }
  return kinds;
}

/** RHS of `childBinding = ...`: kind → env binding map, or `{}` when childless. */
function childBindingLiteral(kinds: string[]): string {
  if (kinds.length === 0) return "{}";
  return `{\n${kinds.map((k) => `    ${JSON.stringify(k)}: "${scream(k)}",`).join("\n")}\n  } as const`;
}

export function emitCloudflare(
  root: RootAgentSpec,
  children: ChildAgentSpec[],
  analysis: Analysis,
  opts: EmitOptions = {}
): CloudflareEmit {
  const rt = opts.runtimeImport ?? "../../src";
  const spec = root.spec;
  const rootClass = `${pascal(spec.agentName)}Durable`;
  const rootBinding = scream(spec.agentName);
  const kids = children.map((c) => {
    const childKinds = childKindsOfSpec(c.spec);
    return {
      ...c,
      className: `${pascal(c.spec.agentName)}Durable`,
      binding: scream(c.spec.agentName),
      // Each child class binds ITS OWN nested children (empty for a leaf). A
      // mid-level agent that composes children gets a real map, not `{}`.
      childBindingSource:
        childKinds.length === 0
          ? "{}; // extend when this agent composes children"
          : `${childBindingLiteral(childKinds)};`,
    };
  });

  // The root binds only its DIRECT children (from its own analysis), not the
  // whole flattened graph — a mid-level child owns the deeper bindings.
  const rootChildBinding = childBindingLiteral(subagentKindsFromAnalysis(analysis));
  const envEntries = [rootBinding, ...kids.map((k) => k.binding)]
    .map((b) => `  ${b}: DurableObjectNamespace;`)
    .join("\n");

  const capabilityMap = [
    ...analysis.static.map((r) => ` *   static  ${r.kind}:${r.name}`),
    ...analysis.dynamic.map((r) => ` *   dynamic ${r.kind}:${r.name} (state-gated)`),
  ].join("\n");

  const agents = `// GENERATED by agent-jsx (compile target: cloudflare/agents). Do not edit.
// You wrote: ${root.componentImport}${kids.map((k) => `, ${k.importPath}`).join("")}
// Everything below is derived binding glue.
/*
 * Root capability surface at compile time:
${capabilityMap}
 */

import { Agent, getAgentByName } from "agents";
import { evaluateTree } from "${rt}/compile/evaluate.ts";
import { collectInfra, collectPrompt } from "${rt}/tree.ts";
import { renderPromptOrFallback } from "${rt}/prompt.ts";
import type { AgentStore } from "${rt}/store.ts";
import type { InfraRecord } from "${rt}/types.ts";
import { ${root.componentName} } from "${root.componentImport}";
${kids.map((k) => `import { ${k.exportName} } from "${k.importPath}";`).join("\n")}
${root.requestHandlerExport && root.requestHandlerImport ? `import { ${root.requestHandlerExport} } from "${root.requestHandlerImport}";` : ""}

/** Root state = the component spec's initial state, widened for the runtime's
 *  own bookkeeping keys (__children/__tasksDone/__self). Derived structurally
 *  from the spec — the state-type string plumbing is gone. */
type RootState = typeof ${root.componentName}.spec.initialState & Record<string, unknown>;

export interface GeneratedEnv {
${envEntries}
}

/** How a child reaches back to its parent — serializable, unlike a closure.
 *  parentName is the canonical Agents instance name; getAgentByName() sets the
 *  PartyServer name before dispatch, which Agent internals expect. parentId is
 *  retained as stable fallback/debug metadata. */
interface CallbackRef {
  binding: keyof GeneratedEnv;
  parentName: string;
  parentId: string;
  child: string;
  event: string;
}

interface ChildRuntimeState {
  __props: Record<string, unknown> | null;
  __callbacks: Record<string, CallbackRef>;
}

type ChildStub = {
  setProps(props: Record<string, unknown>, callbacks: Record<string, CallbackRef>): Promise<void>;
  shutdown(): Promise<void>;
};

/** Authored ticks → wall-clock seconds (compile-time knob). */
const INTERVAL_SCALE = ${opts.intervalScale ?? 1};

/** Real sensor probe. loopy's convention: unreachable = 0; the component's
 *  policy decides what counts as an incident (here: anything !== 200). */
async function probeStatus(url: string): Promise<number> {
  if (!url) return 0;
  try {
    return (await fetch(url, { redirect: "manual" })).status;
  } catch {
    return 0;
  }
}

// ---------------------------------------------------------------------------
// Shared generated runtime: evaluate → diff → apply. ~one screen, no React.

abstract class FiberAgentBase<S extends Record<string, unknown>> extends Agent<GeneratedEnv, S> {
  /** kind → env binding, generated from the composition graph. */
  protected abstract childBinding: Record<string, keyof GeneratedEnv>;
  /** This class's own env binding — how children address callbacks back here. */
  protected abstract selfBinding: keyof GeneratedEnv;
  protected abstract renderTree(state: S): unknown;

  /** Freshest closures from the latest render. Never persisted. */
  #handlers = new Map<string, InfraRecord["handlers"]>();
  /** Serializable config per record (sensor urls etc.), same freshness. */
  #configs = new Map<string, Record<string, unknown>>();
  #reconciling = false;
  #needsReconcile = false;
  #reconcilePromise: Promise<void> | null = null;

  async onStart() {
    // NEVER reconcile inline here. The Agents SDK wraps onStart in
    // blockConcurrencyWhile (input gate CLOSED): if the persisted state has
    // pending work, reconcile spawns children whose immediate RPCs back into
    // this DO (getPdf, onSegment) cannot enter the gate → 30s cancel → DO
    // reset → wake → repeat, a permanent 1101 loop that poisons the instance.
    // Defer to an alarm tick: alarms run with the gate OPEN, exactly like the
    // RPC contexts the pipeline already converges under. (COMPAT-REPORT #34)
    await this.schedule(0, "onAgentEvent", { key: "__wake-reconcile" });
  }
  /** State changed → re-derive infra. REQUEST a reconcile (mark-and-return):
   *  awaiting the in-flight pass from here builds a distributed await-cycle —
   *  parent reconcile #1 awaits child.setProps → child work RPCs back →
   *  parent setState → onStateChanged → awaiting reconcile #1's own promise
   *  never resolves (COMPAT-REPORT #35). The drain loop guarantees a fresh
   *  pass runs after the current one completes. */
  async onStateChanged(_state?: S, _source?: unknown) {
    await this.#requestReconcile();
  }

  /** The Agents SDK reserves render(); agent-jsx renders via renderTree(). */
  render(): void {}

  /** A store bridged to the DO: reads current state, writes via setState. This
   *  is what makes handler closures (store.set(...)) durable — a throwaway
   *  createStore(state) would drop writes on the floor. */
  protected boundStore<T extends Record<string, unknown>>(): AgentStore<T> {
    return {
      get: () => this.state as unknown as T,
      set: (update) => {
        const prev = this.state as unknown as T;
        const next =
          typeof update === "function" ? (update as (p: T) => T)(prev) : { ...prev, ...update };
        this.setState(next as unknown as S);
        this.#needsReconcile = true;
      },
      subscribe: () => () => {},
      snapshot: () => JSON.stringify(this.state),
    };
  }

  /** Durable self-identity. partyserver's \`.name\` is REQUEST-SCOPED — set by
   *  getAgentByName routing, throwing (or varying) on unnamed wakes (alarms,
   *  onStart after eviction). Deriving child names or callback refs from it
   *  raw renames the whole child fleet between contexts → spawn/shutdown
   *  cycling live (invisible under vitest, where every access is named).
   *  First named reconcile persists it; unnamed contexts read the copy.
   *  (COMPAT-REPORT #33) */
  protected selfName(): string | null {
    let live: string | null = null;
    try {
      live = this.name;
    } catch {
      /* unnamed wake */
    }
    const persisted = (this.state as { __self?: string }).__self ?? null;
    if (live && live !== persisted) {
      this.setState({ ...this.state, __self: live } as unknown as S);
    }
    return live ?? persisted;
  }

  /** Render once, capturing the freshest handler closures. Returns desired infra. */
  #renderHandlers(): InfraRecord[] {
    const desired: InfraRecord[] = [];
    for (const r of evaluateTree(this.renderTree(this.state))) collectInfra(r, desired);
    this.#handlers.clear();
    this.#configs.clear();
    for (const rec of desired) {
      this.#handlers.set(\`\${rec.kind}:\${rec.name}\`, rec.handlers);
      this.#configs.set(\`\${rec.kind}:\${rec.name}\`, rec.config);
    }
    return desired;
  }

  /** GENERATED: merge-semantics external write. Raw setState is full-replace
   *  and would nuke runtime bookkeeping (COMPAT-REPORT #3) — workers and UIs
   *  nudge the agent through this instead. */
  async applyState(update: Partial<S>) {
    this.setState({ ...this.state, ...update });
    this.#needsReconcile = true;
    await this.reconcile();
  }

  /** GENERATED: full replacement for generated APIs that need a true reset.
   *  Unlike applyState(), this clears generated bookkeeping such as __tasksDone. */
  async replaceState(next: S) {
    this.setState(next);
    this.#needsReconcile = true;
    await this.reconcile();
  }

  async readState(): Promise<S> {
    return this.state;
  }

  /** GENERATED: typed child accessor — this.subagent(kind, name). */
  protected async subagent(kind: string, name: string) {
    const binding = this.childBinding[kind];
    if (!binding) throw new Error(\`no child binding for kind \${kind}\`);
    return getAgentByName(this.env[binding] as never, name);
  }

  async reconcile() {
    await this.#reconcile(true);
  }

  async #requestReconcile() {
    await this.#reconcile(false);
  }

  async #reconcile(waitForCurrent: boolean) {
    if (this.#reconciling) {
      this.#needsReconcile = true;
      if (waitForCurrent) await this.#reconcilePromise;
      return;
    }
    this.#reconciling = true;
    this.#reconcilePromise = (async () => {
      do {
        this.#needsReconcile = false;
        await this.#reconcileOnce();
      } while (this.#needsReconcile);
    })();
    try {
      await this.#reconcilePromise;
    } finally {
      this.#reconciling = false;
      this.#reconcilePromise = null;
    }
  }

  async #reconcileOnce() {
    const desired = this.#renderHandlers();

    // schedules & sensors: converge durable rows against desired, by payload key
    const timed = desired.filter((r) => r.kind === "schedule" || r.kind === "sensor");
    const live = await this.getSchedules();
    const liveByKey = new Map(live.map((s) => [(s.payload as { key?: string })?.key, s]));
    for (const rec of timed) {
      const key = \`\${rec.kind}:\${rec.name}\`;
      const every = Number(rec.config.every ?? rec.config.interval) * INTERVAL_SCALE;
      if (!liveByKey.has(key))
        await this.schedule(every, "onAgentEvent", { key, rearm: every }, { idempotent: true });
      liveByKey.delete(key);
    }
    for (const stale of liveByKey.values()) if (stale) await this.cancelSchedule(stale.id);

    // subagents: push props + callback refs; despawn removed children
    const wanted = desired.filter((r) => r.kind === "subagent");
    const prev = new Map<string, string>(
      ((this.state as { __children?: { name: string; kind: string }[] }).__children ?? []).map(
        (c) => [c.name, c.kind]
      )
    );
    const self = this.selfName();
    if (!self && wanted.length) {
      // Unnamed wake before any named access: defer child convergence to the
      // next named reconcile rather than minting unstable identities.
      return;
    }
    for (const rec of wanted) {
      const kind = String(rec.config.kind);
      const childName = \`\${self}:\${rec.name}\`;
      const child = (await this.subagent(kind, childName)) as unknown as ChildStub;
      const callbacks: Record<string, CallbackRef> = {};
      for (const event of Object.keys(rec.handlers))
        callbacks[event] = {
          binding: this.selfBinding,
          parentName: self as string,
          parentId: this.ctx.id.toString(),
          child: rec.name,
          event,
        };
      const { kind: _k, ...childProps } = rec.config;
      await child.setProps(childProps, callbacks); // prop change = RPC, like React
      prev.delete(childName);
    }
    for (const [name, kind] of prev) {
      await ((await this.subagent(kind, name)) as unknown as ChildStub).shutdown?.();
    }

    // Persist the child roster for despawn detection — but only when it actually
    // changed, so onStateChanged → reconcile → setState does not loop forever.
    const nextChildren = wanted.map((r) => ({ name: \`\${self}:\${r.name}\`, kind: String(r.config.kind) }));
    const prevJson = JSON.stringify((this.state as { __children?: unknown }).__children ?? []);
    if (JSON.stringify(nextChildren) !== prevJson) {
      this.setState({ ...this.state, __children: nextChildren } as unknown as S);
      this.#needsReconcile = true;
    }

    // one-shot <task> records: run EXACTLY once per name, guarded durably in
    // state. The guard is written BEFORE run()/onDone so the nested
    // onStateChanged → reconcile can never re-run the work.
    const tasksDone = {
      ...((this.state as { __tasksDone?: Record<string, boolean> }).__tasksDone ?? {}),
    };
    for (const rec of desired.filter((r) => r.kind === "task")) {
      if (tasksDone[rec.name]) continue;
      tasksDone[rec.name] = true;
      this.setState({ ...this.state, __tasksDone: { ...tasksDone } } as unknown as S);
      this.#needsReconcile = true;
      const result = await rec.handlers.run?.();
      await rec.handlers.onDone?.(result);
    }
  }

  /** GENERATED single dispatcher: schedules fire here; children call back here.
   *  Renders first so handlers are the freshest closures regardless of eviction. */
  async onAgentEvent(payload: {
    key?: string;
    rearm?: number;
    callback?: { child: string; event: string };
    args?: unknown[];
  }): Promise<unknown> {
    this.#renderHandlers();
    if (payload.callback) {
      // child → parent callback: route to the parent's freshest closure and
      // RETURN its awaited result so a method prop round-trips (request/response).
      // A void event (onResult) resolves to undefined; a method prop (lookupRunbook)
      // resolves to the value the parent's live closure computed. Args + return
      // must be structured-cloneable — DO RPC clones them (COMPAT-REPORT #21).
      const { child, event } = payload.callback;
      const result = await this.#handlers.get(\`subagent:\${child}\`)?.[event]?.(...(payload.args ?? []));
      if (this.#needsReconcile) await this.#requestReconcile();
      return result;
    }
    const key = payload.key ?? "";
    if (key === "__wake-reconcile") {
      // deferred onStart convergence (COMPAT-REPORT #34): alarms run with the
      // input gate open, so pending work can spawn + call back freely here.
      await this.#requestReconcile();
      return;
    }
    const handlers = this.#handlers.get(key);
    // await the handler: onFire/onStatus may themselves await a method prop (a
    // cross-DO round-trip), so the dispatcher must not resolve until that
    // in-flight capability call settles — otherwise the firing DO's I/O context
    // could tear down mid-flight (COMPAT-REPORT #22).
    if (key.startsWith("sensor:")) {
      const status = await probeStatus(String(this.#configs.get(key)?.url ?? ""));
      await handlers?.onStatus?.(status, Date.now());
    } else {
      await handlers?.onFire?.(Date.now());
    }
    if (this.#needsReconcile) await this.#requestReconcile();
    if (payload.rearm) await this.schedule(payload.rearm, "onAgentEvent", payload);
  }

  /** One model turn: the context window is derived from current state. The
   *  <prompt> tree is OPT-IN — when it yields blocks the declarative render
   *  wins (priompt priorities/budget); otherwise the spec's imperative
   *  getPrompt seam; otherwise empty. (agent-jsx part B) */
  promptFor(budgetTokens: number): string {
    const blocks = collectPrompt(evaluateTree(this.renderTree(this.state)));
    return renderPromptOrFallback(blocks, budgetTokens, () => this.imperativePrompt(this.state));
  }

  /** Imperative prompt fallback. Overridden per agent class to route to that
   *  agent's spec.getPrompt; the base has no prompt strategy of its own. */
  protected imperativePrompt(_state: S): string {
    return "";
  }
}

// ---------------------------------------------------------------------------
// Root agent: ${spec.agentName}

// Root props come from the spec's sampleProps (was a per-emit propsJson string).
const ROOT_PROPS = ${JSON.stringify(spec.sampleProps ?? {})} as const;

export class ${rootClass} extends FiberAgentBase<RootState> {
  // Initial state embedded from the spec — no initial-state-export import.
  initialState = ${JSON.stringify(spec.initialState)} as RootState;
  protected selfBinding = "${rootBinding}" as const;
  protected childBinding = ${rootChildBinding};
  protected renderTree(state: RootState): unknown {
    // The root renders its OWN tree via the spec's impl (a bare component call
    // would be a subagent boundary — parent composition).
    return ${root.componentName}.spec.impl({ ...ROOT_PROPS, store: this.boundStore<RootState>() });
  }
  protected imperativePrompt(state: RootState): string {
    return ${root.componentName}.spec.getPrompt?.(state) ?? "";
  }
${root.requestHandlerExport ? `
  async onRequest(req: Request): Promise<Response> {
    return ${root.requestHandlerExport}(req, this);
  }` : ""}
}
${kids
  .map(
    (k) => `
// ---------------------------------------------------------------------------
// Child agent: ${k.spec.agentName} (from ${k.importPath})

export class ${k.className} extends FiberAgentBase<ChildRuntimeState & Record<string, unknown>> {
  initialState = { ...${k.exportName}.spec.initialState, __props: null, __callbacks: {} };
  protected selfBinding = "${k.binding}" as const;
  protected childBinding = ${k.childBindingSource}

  async onStart() {}
  async onStateChanged(_state?: ChildRuntimeState & Record<string, unknown>, _source?: unknown) {}

  /** GENERATED: the parent's prop push. Receiving new props = re-render.
   *  Never work inline while the parent is still awaiting this adoption RPC —
   *  instead self-schedule an immediate gate-open alarm tick, so the child
   *  drives its own <task>/schedule work right after adoption completes.
   *  (An external POST /api/drive still works and is idempotent with this;
   *  COMPAT-REPORT #36.) */
  async setProps(props: Record<string, unknown>, callbacks: Record<string, CallbackRef>) {
    const st = this.state as ChildRuntimeState;
    if (
      JSON.stringify(st.__props) === JSON.stringify(props) &&
      JSON.stringify(st.__callbacks) === JSON.stringify(callbacks)
    ) {
      return;
    }
    this.setState({ ...this.state, __props: props, __callbacks: callbacks });
    await this.schedule(0, "onAgentEvent", { key: "__wake-reconcile" });
  }

  async shutdown() {
    for (const s of await this.getSchedules()) await this.cancelSchedule(s.id);
    this.setState({ ...this.state, __props: null, __children: [] });
  }

  async onRequest(req: Request): Promise<Response> {
    const path = new URL(req.url).pathname;
    if (path.endsWith("/api/drive") && req.method === "POST") {
      await this.reconcile();
      return Response.json({ ok: true, state: this.state }, { headers: { "cache-control": "no-store" } });
    }
    if (path.endsWith("/api/state") && req.method === "GET") {
      return Response.json({ state: this.state }, { headers: { "cache-control": "no-store" } });
    }
    return Response.json({ error: "not found" }, { status: 404, headers: { "cache-control": "no-store" } });
  }

  protected renderTree(state: ChildRuntimeState & Record<string, unknown>): unknown {
    if (!state.__props) return null; // not adopted by a parent yet
    // callbacks arrive as refs; impl sees ordinary functions. A method prop is
    // a capability WITH a return value: the proxy RETURNS the parent
    // dispatcher's result, so awaiting props.lookupRunbook(x) in the child
    // resolves to whatever the parent's freshest closure computed. Fire-and-forget
    // events (onResult) just ignore the resolved undefined.
    const proxied: Record<string, (...args: unknown[]) => Promise<unknown>> = {};
    for (const [event, ref] of Object.entries(state.__callbacks)) {
      proxied[event] = async (...args) => {
        const ns = this.env[ref.binding] as unknown as DurableObjectNamespace;
        const parent = (ref.parentName
          ? await getAgentByName(ns as never, ref.parentName)
          : ns.get(ns.idFromString(ref.parentId))) as unknown as {
          onAgentEvent(p: { callback: { child: string; event: string }; args: unknown[] }): Promise<unknown>;
        };
        return await parent.onAgentEvent({ callback: { child: ref.child, event: ref.event }, args });
      };
    }
    return ${k.exportName}.spec.impl({ ...state.__props, ...proxied, store: this.boundStore() } as never);
  }

  protected imperativePrompt(state: ChildRuntimeState & Record<string, unknown>): string {
    return ${k.exportName}.spec.getPrompt?.(state as never) ?? "";
  }
}`
  )
  .join("\n")}
`;

  const wrangler = `// GENERATED by agent-jsx — merge into wrangler.jsonc
{
  "durable_objects": {
    "bindings": [
      { "name": "${rootBinding}", "class_name": "${rootClass}" }${kids
        .map((k) => `,\n      { "name": "${k.binding}", "class_name": "${k.className}" }`)
        .join("")}
    ]
  },
  "migrations": [
    {
      "tag": "v1",
      "new_sqlite_classes": [${[rootClass, ...kids.map((k) => k.className)]
        .map((c) => `"${c}"`)
        .join(", ")}]
    }
  ]
}
`;

  if (opts.emitRuntimeTo) emitRuntimeFiles(opts.emitRuntimeTo);

  return { agents, wrangler };
}
