/**
 * Compile target #2: flue.
 *
 * Flue's authoring model is eager/static (defineAgent values; @flue/jsx was
 * constructor sugar over it), so the split matters here:
 *   - the STATIC slice (prompt at rest, always-on tools/schedules) compiles
 *     to a defineAgent module;
 *   - the DYNAMIC slice (state-gated subagents/tools) compiles to a
 *     spawnPlan(state) function — the exact shape flue's own design doc
 *     proposed (plans/2026-06-29-jsx-render-prop-subagents.md: "declarative
 *     sugar over dynamic spawn — not a lazy subtree"), with the stable-id
 *     requirement satisfied by our mandatory `name` prop.
 *
 * Emitted as `.ts`, never `.tsx` — flue's discoverModules matches
 * \.(ts|js|mts|mjs)$ only; the .tsx gap is what killed @flue/jsx adoption.
 *
 * API note: `defineAgent`'s initializer returns an `AgentRuntimeConfig`, which
 * has NO `name` field (name comes from the module/route). See COMPAT-REPORT.md
 * — the earlier `name:` guess was an excess property and is removed here.
 */

import { renderPromptOrFallback } from "../prompt.ts";
import { collectPrompt } from "../tree.ts";
import { createStore } from "../store.ts";
import { evaluateComponent } from "./evaluate.ts";
import { emitRuntimeFiles } from "./runtime-files.ts";
import {
  flueChildTargetDiagnostics,
  formatTargetDiagnosticsForComment,
} from "./target-diagnostics.ts";
import type { AgentSpec } from "../agent-component.tsx";
import type { Analysis } from "./analyze.ts";
import type { ChildAgentSpec } from "./emit-cloudflare.ts";

export interface FlueEmitOptions {
  /** The parent agent's spec — the SAME `agentComponent(spec)` the cloudflare
   *  emitter consumes. Supplies agentName, initialState, sampleProps (the flue
   *  task input / resting props), impl (resting render), and the getPrompt seam.
   *  The resting instructions are derived from the spec, not a passed element. */
  spec: AgentSpec;
  model: string;
  /** Export name + import path of the agentComponent — imported for spawnPlan's
   *  `.spec.impl` and structural state typing. */
  componentName: string;
  componentImport: string;
  analysis: Analysis;
  /** Generated child profile modules this parent should expose to flue task delegation. */
  childProfiles?: { importPath: string; profileExportName: string }[];
  promptBudget?: number;
  /** Rewrites the generated runtime imports off `../../src` (e.g. "./runtime"). */
  runtimeImport?: string;
  /** Absolute fs path; when set, the react-free runtime file set is copied here. */
  emitRuntimeTo?: string;
}

export interface FlueChildOptions {
  /** Reserved for symmetry with emitFlue; child profiles import no runtime. */
  runtimeImport?: string;
}

export function flueProfileExportName(agentName: string): string {
  return `${agentName.replace(/[^A-Za-z0-9_$]/g, "_")}Profile`;
}

/**
 * A child agent component → a standalone flue agent profile module. The
 * child's resting <prompt> becomes its instructions; the parent exposes it
 * as a delegation target (flue's harness turns subagents into tools).
 * Props/callbacks note: flue delegation is task-based — parent props become
 * the task input; the callback becomes the awaited task result.
 */
export function emitFlueChild(child: ChildAgentSpec, promptBudget = 400, _opts: FlueChildOptions = {}): string {
  const { spec } = child;
  const profileExport = flueProfileExportName(spec.agentName);
  const diagnostics = formatTargetDiagnosticsForComment(flueChildTargetDiagnostics(child));
  const roots = evaluateComponent(spec.impl, {
    ...(spec.sampleProps ?? {}),
    store: createStore(spec.initialState),
  } as never);
  // Resting instructions: the <prompt> tree if present, else the imperative
  // getPrompt seam at initial state, else empty (agent-jsx part B).
  const instructions = renderPromptOrFallback(
    collectPrompt(roots),
    promptBudget,
    () => spec.getPrompt?.(spec.initialState) ?? ""
  );

  return `// GENERATED by agent-jsx (compile target: flue, child agent). Do not edit.
// Source component: ${child.importPath} (${child.exportName})
${diagnostics ? `${diagnostics}\n` : ""}

import { defineAgentProfile } from "@flue/runtime";

export const ${profileExport} = defineAgentProfile({
  name: ${JSON.stringify(spec.agentName)},
  instructions: ${JSON.stringify(instructions)},
  // Parent props arrive as the delegated task input; the child's onResult
  // callback is realized as the task RETURN value (flue's session.task).
});
`;
}

export function emitFlue(o: FlueEmitOptions): string {
  const rt = o.runtimeImport ?? "../../src";
  const spec = o.spec;
  const childProfiles = o.childProfiles ?? [];
  // Resting instructions derived from the spec: the <prompt> tree rendered at
  // the initial state if present, else the imperative getPrompt seam, else "".
  const restingRoots = evaluateComponent(spec.impl, {
    ...(spec.sampleProps ?? {}),
    store: createStore(spec.initialState),
  } as never);
  const instructions = renderPromptOrFallback(
    collectPrompt(restingRoots),
    o.promptBudget ?? 400,
    () => spec.getPrompt?.(spec.initialState) ?? ""
  );

  const dynamicKinds = o.analysis.dynamic.map((r) => `${r.kind}:${r.name}`);
  const childImports = childProfiles
    .map((c) => `import { ${c.profileExportName} } from "${c.importPath}";`)
    .join("\n");
  const subagentsLine =
    childProfiles.length > 0
      ? `  // Declared subagent profiles are flue's binding table for session.task(..., { agent }).\n  subagents: [${childProfiles.map((c) => c.profileExportName).join(", ")}],\n`
      : "";

  const module = `// GENERATED by agent-jsx (compile target: flue). Do not edit.
// Plain .ts on purpose: flue's discoverModules excludes .tsx — a discovered
// .ts entry importing the .tsx component is the sanctioned pattern.
//
// Static instructions below are the component's <prompt> rendered at the
// resting state. Live context (incidents etc.) is dynamic — re-render the
// component per turn and pass renderPrompt(...) as the task context instead
// of baking it here.

import { defineAgent } from "@flue/runtime";
import { evaluateTree } from "${rt}/compile/evaluate.ts";
import { collectInfra } from "${rt}/tree.ts";
import { createStore } from "${rt}/store.ts";
import { ${o.componentName} } from "${o.componentImport}";
${childImports}

// State + props derived structurally from the component spec (no state-type
// string, no per-emit propsJson): the spec is the single analyzed source.
type State = typeof ${o.componentName}.spec.initialState & Record<string, unknown>;
const PROPS = ${JSON.stringify(spec.sampleProps ?? {})} as const;

// defineAgent's initializer returns an AgentRuntimeConfig (model/instructions/
// tools/subagents/…). No \`name\` field — flue derives the agent name from the
// module/route, not the config object.
export default defineAgent(() => ({
  model: ${JSON.stringify(o.model)},
  instructions: ${JSON.stringify(instructions)},
${subagentsLine}
  // No static tools: the component's <tool> is state-gated (e.g. page-oncall
  // only during an incident). Surface it per-turn via the harness rather than
  // as an always-on definition tool. flue has no sensor primitive either —
  // poll sensors belong in a flue workflow (cron) that calls session.prompt
  // with fresh observations.
}));

/**
 * Dynamic residue${dynamicKinds.length ? ` (${dynamicKinds.join(", ")})` : ""}: flue's runtime has no state→render
 * loop, so state-gated children compile to a spawn plan the orchestrating
 * workflow calls after each state change. Stable ids come from \`name\` —
 * "the #1 production bug" per flue's render-prop plan, solved by contract.
 * Child props are spread into the boundary config, so the delegated task input
 * is config minus the reserved \`kind\` discriminator.
 */
export function spawnPlan(state: State) {
  const store = createStore<State>(state);
  // .spec.impl renders the agent's OWN tree; a bare component call would be a
  // subagent boundary (parent composition), collapsing the whole plan to one.
  const desired = evaluateTree(${o.componentName}.spec.impl({ ...PROPS, store })).flatMap((root) =>
    collectInfra(root)
  );
  return desired
    .filter((r) => r.kind === "subagent")
    .map((r) => {
      const { kind, ...input } = r.config;
      return { stableId: r.name, agent: String(kind), input };
    });
}
`;

  if (o.emitRuntimeTo) emitRuntimeFiles(o.emitRuntimeTo);

  return module;
}

export interface FlueWorkflowOptions {
  /** The workflow agent's spec — supplies agentName (the agent binding),
   *  initialState (the input fallback), sampleProps (props), and impl (the
   *  component the reactive loop re-evaluates each round). */
  spec: AgentSpec;
  componentName: string;
  /** Import path to the .tsx component (bun/flue resolve a .ts→.tsx import). */
  componentImport: string;
  /** The generated defineAgent module — its DEFAULT export is the workflow agent. */
  agentModuleImport: string;
  /** Rewrites the runtime import off `../../src` (e.g. "./runtime"). */
  runtimeImport?: string;
  /** Absolute fs path; when set, the react-free runtime file set is copied here. */
  emitRuntimeTo?: string;
}

/**
 * The flue-side completer for v0.5's dynamic residue: a real `defineWorkflow`
 * whose run() drives `runReactiveWorkflow`, with `delegate` wired to
 * `session.task`. flue has no state→render loop, so this workflow IS the loop —
 * it re-evaluates the component per round and delegates fresh `<subagent>`
 * records until the composition is at rest.
 *
 * Verified against the REAL @flue/runtime (~/dev/flue, read-only), see
 * COMPAT-REPORT.md #12–#15:
 *   - `defineWorkflow({ agent, input, run })` folds run() into an `action` and
 *     returns a frozen `{ __flueWorkflowDefinition, agent, action }`
 *     (workflow-definition.ts:52-105). `agent` must pass `isAgentDefinition`,
 *     so we import the generated `defineAgent` module's default export.
 *   - run() receives an `ActionContext = { harness, log, input }`
 *     (action.ts:18-23) — NOT `{ harness, input }` verbatim; `session` is
 *     obtained via `context.harness.session()` (types.ts:462-469).
 *   - `input` MUST be a top-level object schema; `defineAction` throws
 *     otherwise (action.ts:83-85, schema.ts:42-45). `v.object(...)` qualifies;
 *     state is nested under `{ state }`.
 *   - delegation: `session.task(text, { agent }) → { text }`
 *     (types.ts:552-556 task, :674-683 TaskOptions.agent, :620-627 PromptResponse).
 */
export function emitFlueWorkflow(o: FlueWorkflowOptions): string {
  const rt = o.runtimeImport ?? "../../src";
  const spec = o.spec;
  const agentBinding = `${spec.agentName}Agent`;

  const module = `// GENERATED by agent-jsx (compile target: flue, reactive workflow). Do not edit.
// Plain .ts on purpose: flue's discoverModules excludes .tsx — a discovered
// .ts entry importing the .tsx component is the sanctioned pattern.
//
// flue has no state→render loop, so this workflow's run() IS the loop: it
// drives runReactiveWorkflow, which re-evaluates the component each round,
// delegates every fresh <subagent> via session.task, and folds each result
// back through that record's onResult until the composition is at rest.
//
// Real flue API shape (verified against ~/dev/flue, read-only):
//   - defineWorkflow({ agent, input, run }) folds run() into \`action\` and
//     returns a frozen { __flueWorkflowDefinition, agent, action }
//     (workflow-definition.ts:52-105). \`agent\` must pass isAgentDefinition,
//     hence the generated defineAgent module's default export.
//   - run(context) receives an ActionContext = { harness, log, input }
//     (action.ts:18-23); the session comes from context.harness.session()
//     (types.ts:462-469), NOT a top-level \`session\`.
//   - \`input\` MUST be a top-level object schema or defineAction throws
//     (action.ts:83-85; schema.ts:42-45 accepts type 'object'), so state is
//     nested under { state }.
//   - delegation is session.task(text, { agent }) → { text }
//     (types.ts:552-556, :674-683, :620-627).

import * as v from "valibot";
import { defineWorkflow } from "@flue/runtime";
import { runReactiveWorkflow } from "${rt}/workflow-executor.ts";
import ${agentBinding} from "${o.agentModuleImport}";
import { ${o.componentName} } from "${o.componentImport}";

// State + props derived structurally from the component spec (no state-type
// string, no initial-state-export import, no per-emit propsJson).
type State = typeof ${o.componentName}.spec.initialState & Record<string, unknown>;
const PROPS = ${JSON.stringify(spec.sampleProps ?? {})};

export default defineWorkflow({
  agent: ${agentBinding},
  // Top-level v.object is a flue load-time rule (defineAction validates the
  // schema is a top-level object). The reactive turn enters at a caller-supplied
  // state — what the sensor/poll turn produced — nested under { state }.
  input: v.object({ state: v.any() }),
  run: async (context) => {
    const session = await context.harness.session();
    const initialState = (context.input.state ?? ${o.componentName}.spec.initialState) as State;
    return runReactiveWorkflow({
      // .spec.impl renders the agent's OWN tree each round (a bare component
      // call would be a subagent boundary — parent composition).
      component: ${o.componentName}.spec.impl,
      props: PROPS,
      initialState,
      // Each SpawnDescriptor { stableId, agent, input } → one delegated flue
      // task. The subagent kind selects the named subagent profile; the task's
      // result text is folded back into state through the record's onResult.
      delegate: async (descriptor) => {
        const response = await session.task(
          \`Investigate "\${descriptor.stableId}" via the "\${descriptor.agent}" agent. Input: \${JSON.stringify(descriptor.input)}.\`,
          { agent: descriptor.agent },
        );
        return response.text;
      },
    });
  },
});
`;

  if (o.emitRuntimeTo) emitRuntimeFiles(o.emitRuntimeTo);

  return module;
}
