/**
 * Compile target: flue 2.0 (function agents).
 *
 * Flue 1.x was compile-once: the emitter evaluated the resting render and
 * froze it into `defineAgentProfile` values, with a workflow module emulating
 * a state→render loop on top. Flue 2.0 agents are FUNCTIONS the session
 * re-renders every turn (hooks resolve against a per-render frame; durable
 * `usePersistentState` writes surface on the next render) — the loop is
 * native. This emitter therefore generates no evaluated content at all: the
 * module forwards the authored definition and the flue hooks to
 * `renderFlue2Agent`, and every turn's harness is derived from live state.
 */

export interface Flue2EmitOptions {
  /** Supplies `agentName` for the generated function name. Nothing else is
   *  read — the whole point of the target is that content is NOT compiled. */
  spec: { agentName: string };
  /** Module path of the authored `*.agent.tsx` (default export). */
  sourceImport: string;
  /** Local name the definition is imported under. */
  exportName: string;
  /** Import base for the react-free runtime (default `../../src/compile`). */
  runtimeImport?: string;
  /** Prompt budget baked into the module (chars/4, priompt-lite). */
  promptBudget?: number;
}

/** `openai-chess-player` → `OpenaiChessPlayer`; flue agent functions are
 *  PascalCase by convention and must be valid identifiers. */
function flue2FunctionName(agentName: string): string {
  const pascal = agentName
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((part) => part[0]!.toUpperCase() + part.slice(1))
    .join("");
  const name = pascal || "Agent";
  return /^[A-Za-z_$]/.test(name) ? name : `_${name}`;
}

export function emitFlue2(options: Flue2EmitOptions): string {
  const fnName = flue2FunctionName(options.spec.agentName);
  const runtimeBase = options.runtimeImport ?? "../../src/compile";
  const budget = options.promptBudget ?? 400;

  return `// GENERATED by agent-jsx (compile target: flue 2.0, function agent). Do not edit.
// Source definition: ${options.sourceImport} (${options.exportName})
'use agent';

import { useModel, usePersistentState, useTool } from "@flue/runtime";
import ${options.exportName} from "${options.sourceImport}";
import { renderFlue2Agent } from "${runtimeBase}/flue2-runtime.ts";

export default function ${fnName}() {
  return renderFlue2Agent(${options.exportName}, { useModel, usePersistentState, useTool }, { promptBudget: ${budget} });
}
`;
}
