/**
 * Compiler-owned lowering for one hierarchy-free, Cloudflare-style agent class.
 * The authored file owns state, model, prompts/tools/skills, and @callable
 * methods. This tiny generated companion turns it into a composable JSX
 * boundary; parent/child relationships remain exclusively in composition JSX.
 */

export interface AgentModuleEmitOptions {
  /** Import path from the generated companion to the authored *.agent.tsx. */
  sourceImport: string;
  /** Public generated component export, e.g. OpenAIAgent. */
  exportName: string;
  /** Import path from the companion to agent-class.tsx. */
  runtimeImport?: string;
}

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

function assertIdentifier(value: string, label: string): void {
  if (!IDENTIFIER.test(value)) {
    throw new Error(`[agent-jsx] ${label} must be a JavaScript identifier; received ${JSON.stringify(value)}`);
  }
}

/** Emit the tiny boundary companion consumed by composition and target emitters. */
export function emitAgentModule(options: AgentModuleEmitOptions): string {
  const runtimeImport = options.runtimeImport ?? "agent-jsx/agent";
  assertIdentifier(options.exportName, "exportName");

  return `// GENERATED by agent-jsx from ${options.sourceImport}. Do not edit.
// Class-to-boundary lowering is compiler-owned; hierarchy lives in composition JSX.

import AgentDefinition from ${JSON.stringify(options.sourceImport)};
import { compileAgentClass } from ${JSON.stringify(runtimeImport)};

export const ${options.exportName} = compileAgentClass(AgentDefinition);

export default ${options.exportName};
`;
}
