export interface ClientActionSpec {
  /** Discriminant passed to the authored reducer. */
  type: string;
  /** HTTP endpoint, e.g. /api/try-harder. */
  path: string;
  /** Generated client method name. */
  methodName: string;
  /** TypeScript parameter list for the generated client method. */
  params?: string;
  /** JavaScript object expression sent as the POST body. */
  body?: string;
  /** Use replaceState instead of applyState after this action succeeds. */
  replaceState?: boolean;
}

export interface ClientApiSpec {
  agentName: string;
  bindingName: string;
  stateTypeName: string;
  stateImport: string;
  actionsImport: string;
  snapshotExport: string;
  reducerExport: string;
  actionTypeName: string;
  clientName: string;
  promptBudget?: number;
  title?: string;
  actions: ClientActionSpec[];
}

export interface ClientApiEmit {
  api: string;
}

const pascal = (s: string) => s.replace(/(?:^|[-_:])(\w)/g, (_, c) => c.toUpperCase());
const kebab = (s: string) =>
  s === s.toUpperCase() && s !== s.toLowerCase()
    ? s.toLowerCase().replace(/_/g, "-")
    : s
        .replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`)
        .replace(/^-/, "")
        .replace(/_/g, "-");

export function emitCloudflareClientApi(spec: ClientApiSpec): ClientApiEmit {
  const name = pascal(spec.agentName);
  const namespace = kebab(spec.bindingName);
  const promptBudget = spec.promptBudget ?? 220;
  const title = spec.title ?? name;
  const handleName = `handle${name}Api`;
  const handleAgentName = `handle${name}AgentRequest`;
  const renderName = `render${name}Page`;
  const replaceTypes = spec.actions.filter((action) => action.replaceState).map((action) => action.type);

  const routes = spec.actions
    .map(
      (action) => `  if (path === ${JSON.stringify(action.path)} && req.method === "POST") {
    const input = await readJson(req);
    return actionResponse(agent, { type: ${JSON.stringify(action.type)}, ...(input ?? {}) } as ${spec.actionTypeName});
  }`
    )
    .join("\n");

  const clientMethods = spec.actions
    .map(
      (action) => `  async ${action.methodName}(${action.params ?? ""}) {
    return this.post(${JSON.stringify(action.path)}, ${action.body ?? "{}"});
  }`
    )
    .join("\n\n");

  const api = `// GENERATED by agent-jsx (compile target: cloudflare client/API). Do not edit.
// You wrote the state reducer in ${spec.actionsImport}; this file is HTTP/client/page glue.

import { routeAgentRequest } from "agents";
import type { ${spec.stateTypeName} } from "${spec.stateImport}";
import { ${spec.snapshotExport}, ${spec.reducerExport}, type ${spec.actionTypeName} } from "${spec.actionsImport}";

interface Env {
  ${spec.bindingName}: DurableObjectNamespace;
}

export type ${name}AgentRequestHost = {
  readState(): Promise<${spec.stateTypeName}>;
  applyState(update: Partial<${spec.stateTypeName}>): Promise<void>;
  replaceState?(next: ${spec.stateTypeName}): Promise<void>;
  promptFor(budgetTokens: number): string;
};

const PROMPT_BUDGET = ${promptBudget};
const REPLACE_ACTIONS = new Set<string>(${JSON.stringify(replaceTypes)});
const AGENT_NAMESPACE = ${JSON.stringify(namespace)};

function json(data: unknown, status = 200): Response {
  return Response.json(data, {
    status,
    headers: { "cache-control": "no-store" },
  });
}

async function readJson(req: Request): Promise<Record<string, unknown> | null> {
  const text = await req.text();
  if (!text.trim()) return null;
  return JSON.parse(text) as Record<string, unknown>;
}

function routedPath(url: URL): string {
  const parts = url.pathname.split("/").filter(Boolean);
  if (parts[0] === "agents" && parts.length >= 3) {
    return "/" + parts.slice(3).join("/");
  }
  return url.pathname;
}

async function snapshotResponse(agent: ${name}AgentRequestHost): Promise<Response> {
  return json(${spec.snapshotExport}(await agent.readState(), agent.promptFor(PROMPT_BUDGET)));
}

async function actionResponse(agent: ${name}AgentRequestHost, action: ${spec.actionTypeName}): Promise<Response> {
  const result = ${spec.reducerExport}(await agent.readState(), action);
  if (result.ok) {
    if (REPLACE_ACTIONS.has((action as { type: string }).type) && agent.replaceState) {
      await agent.replaceState(result.state);
    } else {
      await agent.applyState(result.state);
    }
  }
  const next = await agent.readState();
  return json({
    ...result,
    snapshot: ${spec.snapshotExport}(next, agent.promptFor(PROMPT_BUDGET)),
  }, result.ok ? 200 : 409);
}

export async function ${handleAgentName}(req: Request, agent: ${name}AgentRequestHost): Promise<Response> {
  const path = routedPath(new URL(req.url));
  if (path === "/api/state" && req.method === "GET") {
    return snapshotResponse(agent);
  }
${routes}
  return json({ error: "not found" }, 404);
}

export class ${spec.clientName} {
  constructor(
    private readonly baseUrl = "",
    private readonly agent = "main"
  ) {}

  private url(path: string): string {
    const encodedAgent = encodeURIComponent(this.agent);
    const normalizedPath = path.startsWith("/") ? path : \`/\${path}\`;
    const url = new URL(
      \`/agents/\${AGENT_NAMESPACE}/\${encodedAgent}\${normalizedPath}\`,
      this.baseUrl || "http://local.agent-jsx"
    );
    return this.baseUrl ? url.toString() : \`\${url.pathname}\${url.search}\`;
  }

  async state() {
    const res = await fetch(this.url("/api/state"));
    if (!res.ok) throw new Error(await res.text());
    return res.json();
  }

  private async post(path: string, body: Record<string, unknown>) {
    const res = await fetch(this.url(path), {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify(body),
    });
    if (!res.ok && res.status !== 409) throw new Error(await res.text());
    return res.json();
  }

${clientMethods}
}

export function ${renderName}(): string {
  return \`<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${title}</title>
  <style>
    :root { color-scheme: light; font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }
    body { margin: 0; background: #f7f7f4; color: #1d2522; }
    main { width: min(1040px, calc(100vw - 32px)); margin: 32px auto; display: grid; gap: 18px; }
    header { display: flex; justify-content: space-between; align-items: end; gap: 16px; border-bottom: 1px solid #c9cec7; padding-bottom: 14px; }
    h1 { margin: 0; font-size: 26px; line-height: 1.1; letter-spacing: 0; }
    .status { font-size: 13px; color: #53605b; }
    .panel { background: #fff; border: 1px solid #d7dbd4; border-radius: 8px; padding: 16px; box-shadow: 0 1px 2px rgba(26, 34, 30, 0.06); }
    .controls { display: flex; gap: 10px; flex-wrap: wrap; }
    .channel { display: flex; align-items: center; gap: 12px; flex-wrap: wrap; }
    label { color: #53605b; }
    input[type="file"] { font: inherit; max-width: 100%; }
    button { border: 1px solid #1d2522; background: #1d2522; color: white; border-radius: 6px; padding: 9px 13px; font: inherit; cursor: pointer; }
    button.secondary { background: white; color: #1d2522; }
    button:disabled { opacity: .45; cursor: not-allowed; }
    dl { display: grid; grid-template-columns: 130px 1fr; gap: 8px 14px; margin: 0; }
    dt { color: #53605b; }
    dd { margin: 0; }
    pre { white-space: pre-wrap; overflow-wrap: anywhere; background: #f1f2ee; border-radius: 6px; padding: 12px; margin: 0; }
    .candidate { display: grid; gap: 10px; }
    ul { margin: 0; padding-left: 18px; }
  </style>
</head>
<body>
  <main>
    <header>
      <div>
        <h1>${title}</h1>
        <div class="status" id="session"></div>
      </div>
      <div class="controls">
        <button id="try">Try harder</button>
        <button id="ok" class="secondary">OK</button>
        <button id="reset" class="secondary">Reset</button>
      </div>
    </header>
    <section class="panel channel">
      <label for="doc">PDF</label>
      <input id="doc" type="file" accept="application/pdf" />
      <span class="status" id="doc-status"></span>
    </section>
    <section class="panel"><dl id="summary"></dl></section>
    <section class="panel candidate" id="candidate"></section>
    <section class="panel"><pre id="prompt"></pre></section>
  </main>
  <script type="module">
    const params = new URLSearchParams(location.search);
    if (!params.get("agent")) {
      params.set("agent", crypto.randomUUID());
      history.replaceState(null, "", "?" + params.toString());
    }
    const agent = params.get("agent");
    const withAgent = (path) => {
      const normalizedPath = path.startsWith("/") ? path : "/" + path;
      return new URL("/agents/${namespace}/" + encodeURIComponent(agent) + normalizedPath, location.href);
    };
    const childUrl = (kind, name, path) => {
      const normalizedPath = path.startsWith("/") ? path : "/" + path;
      return new URL("/agents/" + kind + "/" + name + normalizedPath, location.href);
    };
    async function api(path, body) {
      const init = body ? { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) } : {};
      const res = await fetch(withAgent(path), init);
      return res.json();
    }
    async function driveChildren(snapshot) {
      const children = (snapshot && snapshot.state && snapshot.state.__children) || [];
      if (!Array.isArray(children) || children.length === 0) return false;
      await Promise.all(children.map((child) => {
        if (!child || !child.kind || !child.name) return null;
        return fetch(childUrl(child.kind, child.name, "/api/drive"), { method: "POST" }).catch(() => null);
      }));
      return true;
    }
    function esc(value) {
      return String(value ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
    }
    function toBase64(buffer) {
      const bytes = new Uint8Array(buffer);
      let binary = "";
      for (let i = 0; i < bytes.length; i += 32768) {
        binary += String.fromCharCode(...bytes.subarray(i, i + 32768));
      }
      return btoa(binary);
    }
    function render(snapshot) {
      document.querySelector("#session").textContent = "session " + agent;
      document.querySelector("#try").disabled = !snapshot.controls.tryHarder;
      document.querySelector("#ok").disabled = !snapshot.controls.ok;
      const latest = snapshot.latestCandidate;
      const source = snapshot.state.source;
      document.querySelector("#summary").innerHTML =
        "<dt>Status</dt><dd>" + esc(snapshot.status) + "</dd>" +
        "<dt>Document</dt><dd>" + esc(source ? source.name : "waiting") + "</dd>" +
        "<dt>Attempts</dt><dd>" + snapshot.state.candidates.length + " / " + snapshot.state.requestedAttempts + "</dd>" +
        "<dt>Text layer</dt><dd>" + (snapshot.state.textLayer ? snapshot.state.textLayer.length + " chars" : (source ? "extracting" : "not started")) + "</dd>" +
        "<dt>Accepted</dt><dd>" + esc(snapshot.state.acceptedId || "not yet") + "</dd>";
      document.querySelector("#candidate").innerHTML = latest ? (
        "<strong>" + esc(latest.id) + " - " + esc(latest.label) + " (" + Math.round(latest.confidence * 100) + "%)</strong>" +
        "<div>" + esc(latest.payload.summary) + "</div>" +
        "<ul>" + latest.payload.extractedFacts.map((fact) => "<li>" + esc(fact) + "</li>").join("") + "</ul>" +
        (latest.payload.openQuestions.length ? "<div>Open: " + esc(latest.payload.openQuestions.join("; ")) + "</div>" : "")
      ) : (source ? "Waiting for first candidate." : "Waiting for document.");
      document.querySelector("#prompt").textContent = snapshot.prompt || "";
    }
    async function refresh() {
      let snapshot = await api("/api/state");
      if (await driveChildren(snapshot)) snapshot = await api("/api/state");
      render(snapshot);
    }
    document.querySelector("#try").addEventListener("click", async () => { const result = await api("/api/try-harder", {}); await driveChildren(result.snapshot); await refresh(); });
    document.querySelector("#ok").addEventListener("click", async () => { render((await api("/api/ok", {})).snapshot); });
    document.querySelector("#reset").addEventListener("click", async () => { render((await api("/api/reset", {})).snapshot); });
    document.querySelector("#doc").addEventListener("change", async (event) => {
      const file = event.target.files && event.target.files[0];
      if (!file) return;
      document.querySelector("#doc-status").textContent = "loading " + file.name;
      const pdfB64 = toBase64(await file.arrayBuffer());
      const result = await api("/api/channels/document", {
        channel: "document",
        document: { name: file.name, mediaType: file.type || "application/pdf", pdfB64 }
      });
      document.querySelector("#doc-status").textContent = result.ok ? file.name : (result.reason || "rejected");
      await driveChildren(result.snapshot);
      await refresh();
    });
    await refresh();
    setInterval(refresh, 1200);
  </script>
</body>
</html>\`;
}

export async function ${handleName}(req: Request, env: Env): Promise<Response> {
  const url = new URL(req.url);
  if (url.pathname === "/" && req.method === "GET") {
    return new Response(${renderName}(), { headers: { "content-type": "text/html; charset=utf-8" } });
  }
  if (url.pathname === "/favicon.ico" && req.method === "GET") {
    return new Response(null, { status: 204 });
  }
  const routed = await routeAgentRequest(req, env);
  if (routed) return routed;
  return json({ error: "not found" }, 404);
}

export default { fetch: ${handleName} };
`;

  return { api };
}
