// GENERATED by agent-jsx (compile target: flue, child agent). Do not edit.
// Source component: ../agents/bbox-extractor.tsx (BboxExtractor)
// TARGET WARNING [flue-child-state-not-durable]: child initialState keys [extracted] are used only to render the flue profile instructions; the flue task-profile target does not persist a child AgentStore.
// TARGET WARNING [flue-child-infra-not-emitted]: child infra [task:extract:sample] is not emitted into defineAgentProfile; the flue target exposes this child as a session.task profile.


import { defineAgentProfile } from "@flue/runtime";

export const bbox_extractorProfile = defineAgentProfile({
  name: "bbox-extractor",
  instructions: "[system] You extract the text layer of ONE region (sample) of a PDF page.\nextraction pending.",
  // Parent props arrive as the delegated task input; the child's onResult
  // callback is realized as the task RETURN value (flue's session.task).
});
