// GENERATED by agent-jsx (compile target: flue, child agent). Do not edit.
// Source component: ../agents/investigator.tsx (Investigator)
// TARGET WARNING [flue-child-state-not-durable]: child initialState keys [checked] are used only to render the flue profile instructions; the flue task-profile target does not persist a child AgentStore.
// TARGET WARNING [flue-child-infra-not-emitted]: child infra [tool:fetch-logs, tool:check-upstream, schedule:sla-deadline] is not emitted into defineAgentProfile; the flue target exposes this child as a session.task profile.


import { defineAgentProfile } from "@flue/runtime";

export const investigatorProfile = defineAgentProfile({
  name: "investigator",
  instructions: "[system] You investigate ONE outage: https://example.com, down since t=0. Find the root cause, then call onResult exactly once.\nChecked so far: nothing yet.\nPlaybook: DNS → upstream deps → recent deploys → capacity.",
  // Parent props arrive as the delegated task input; the child's onResult
  // callback is realized as the task RETURN value (flue's session.task).
});
