// GENERATED by agent-jsx (compile target: flue, child agent). Do not edit.
// Source component: ../agents/layout-reviewer.tsx (LayoutReviewer)
// TARGET WARNING [flue-child-state-not-durable]: child initialState keys [segments] are used only to render the flue profile instructions; the flue task-profile target does not persist a child AgentStore.


import { defineAgentProfile } from "@flue/runtime";
import { evaluateTree } from "./runtime/compile/evaluate.ts";
import { collectInfra } from "./runtime/tree.ts";
import { createStore } from "./runtime/store.ts";
import { LayoutReviewer } from "../agents/layout-reviewer.tsx";
import { bbox_extractorProfile } from "./bbox-extractor.flue.ts";

export const layout_reviewerProfile = defineAgentProfile({
  name: "layout-reviewer",
  instructions: "[system] Review layout regions; delegate bbox extraction as needed.\n0 regions detected; 0 read so far.",
  // Nested subagent profiles — this level's static hierarchy as flue's native
  // `subagents:` array (defineAgentProfile carrying subagents, exactly the
  // sketch). session.task(..., { agent }) resolves them.
  subagents: [bbox_extractorProfile],
});

// State derived structurally from the component spec.
type State = typeof LayoutReviewer.spec.initialState & Record<string, unknown>;
const PROPS = {"page":null} as const;

/**
 * Dynamic residue (subagent:bbox:main:r1, subagent:bbox:main:r2): this profile fans out one
 * nested child per item in its delegated INPUT (a `.map` over pushed-down
 * props). flue's static profile text cannot encode that count, so the
 * deterministic plan is a function of the task input. Static nested children
 * are declared on `subagents` above and excluded here by stable id.
 */
const STATIC_SUBAGENTS = new Set(["bbox:main:header"]);
export function spawnPlan(input: Record<string, unknown> = PROPS, state: State = LayoutReviewer.spec.initialState as State) {
  const store = createStore<State>(state);
  const desired = evaluateTree(LayoutReviewer.spec.impl({ ...PROPS, ...input, store } as never)).flatMap((root) =>
    collectInfra(root)
  );
  return desired
    .filter((r) => r.kind === "subagent" && !STATIC_SUBAGENTS.has(r.name))
    .map((r) => {
      const { kind, ...childInput } = r.config;
      return { stableId: r.name, agent: String(kind), input: childInput };
    });
}
