// GENERATED by agent-jsx (compile target: flue, child agent). Do not edit.
// Source component: ../agents/layout-reviewer.tsx (LayoutReviewer)
// TARGET WARNING [flue-child-state-not-durable]: child initialState keys [detected] are used only to render the flue profile instructions; the flue task-profile target does not persist a child AgentStore.


import { defineAgentProfile } from "@flue/runtime";

export const layout_reviewerProfile = defineAgentProfile({
  name: "layout-reviewer",
  instructions: "[system] Detect the layout regions of the page; emit their bounding boxes for extraction.\nwaiting for a page",
  // Parent props arrive as the delegated task input; the child's onResult
  // callback is realized as the task RETURN value (flue's session.task).
});
