// GENERATED by agent-jsx (compile target: flue, child agent). Do not edit.
// Source component: ../agents/worker.tsx (Worker)
// TARGET WARNING [flue-child-state-not-durable]: child initialState keys [answered] are used only to render the flue profile instructions; the flue task-profile target does not persist a child AgentStore.
// TARGET WARNING [flue-child-infra-not-emitted]: child infra [task:answer:sample] is not emitted into defineAgentProfile; the flue target exposes this child as a session.task profile.


import { defineAgentProfile } from "@flue/runtime";

export const tool_workerProfile = defineAgentProfile({
  name: "tool-worker",
  description: "Answer a research query from the document corpus.",
  instructions: "[system] Answer one research query (sample).\nresearching…",
  // Parent props arrive as the delegated task input; the child's onResult
  // callback is realized as the task RETURN value (flue's session.task).
});
