// GENERATED by agent-jsx (compile target: flue, child agent). Do not edit.
// Source component: ../agents/summarizer.tsx (Summarizer)
// TARGET WARNING [flue-child-state-not-durable]: child initialState keys [answered] are used only to render the flue profile instructions; the flue task-profile target does not persist a child AgentStore.
// TARGET WARNING [flue-child-infra-not-emitted]: child infra [task:summarize:sample] is not emitted into defineAgentProfile; the flue target exposes this child as a session.task profile.


import { defineAgentProfile } from "@flue/runtime";

export const tool_summarizerProfile = defineAgentProfile({
  name: "tool-summarizer",
  description: "Summarize the document corpus for a query.",
  instructions: "[system] Summarize the corpus for one query (sample).\nsummarizing…",
  // Parent props arrive as the delegated task input; the child's onResult
  // callback is realized as the task RETURN value (flue's session.task).
});
