// GENERATED by agent-jsx (compile target: flue, reactive workflow). Do not edit.
// Plain .ts on purpose: flue's discoverModules excludes .tsx — a discovered
// .ts entry importing the .tsx component is the sanctioned pattern.
//
// flue has no state→render loop, so this workflow's run() IS the loop: it
// drives runReactiveWorkflow, which re-evaluates the component each round,
// delegates every fresh <subagent> via session.task, and folds each result
// back through that record's onResult until the composition is at rest.
//
// Real flue API shape (verified against ~/dev/flue, read-only):
//   - defineWorkflow({ agent, input, run }) folds run() into `action` and
//     returns a frozen { __flueWorkflowDefinition, agent, action }
//     (workflow-definition.ts:52-105). `agent` must pass isAgentDefinition,
//     hence the generated defineAgent module's default export.
//   - run(context) receives an ActionContext = { harness, log, input }
//     (action.ts:18-23); the session comes from context.harness.session()
//     (types.ts:462-469), NOT a top-level `session`.
//   - `input` MUST be a top-level object schema or defineAction throws
//     (action.ts:83-85; schema.ts:42-45 accepts type 'object'), so state is
//     nested under { state }.
//   - delegation is session.task(text, { agent }) → { text }
//     (types.ts:552-556, :674-683, :620-627).

import * as v from "valibot";
import { defineWorkflow } from "@flue/runtime";
import { runReactiveWorkflow } from "./runtime/workflow-executor.ts";
import uptimeAgent from "./uptime.flue.ts";
import { UptimeAgent } from "../agents/uptime-agent.tsx";

// State + props derived structurally from the component spec (no state-type
// string, no initial-state-export import, no per-emit propsJson).
type State = typeof UptimeAgent.spec.initialState & Record<string, unknown>;
const PROPS = {"sites":["https://a.example","https://b.example","https://c.example"]};

export default defineWorkflow({
  agent: uptimeAgent,
  // Top-level v.object is a flue load-time rule (defineAction validates the
  // schema is a top-level object). The reactive turn enters at a caller-supplied
  // state — what the sensor/poll turn produced — nested under { state }.
  input: v.object({ state: v.any() }),
  run: async (context) => {
    const session = await context.harness.session();
    const initialState = (context.input.state ?? UptimeAgent.spec.initialState) as State;
    return runReactiveWorkflow({
      // .spec.impl renders the agent's OWN tree each round (a bare component
      // call would be a subagent boundary — parent composition).
      component: UptimeAgent.spec.impl,
      props: PROPS,
      initialState,
      // Each SpawnDescriptor { stableId, agent, input } → one delegated flue
      // task. The subagent kind selects the named subagent profile; the task's
      // result text is folded back into state through the record's onResult.
      delegate: async (descriptor) => {
        const response = await session.task(
          `Run "${descriptor.stableId}" with the "${descriptor.agent}" agent. Input: ${JSON.stringify(descriptor.input)}.`,
          { agent: descriptor.agent },
        );
        return response.text;
      },
    });
  },
});
