// GENERATED by agent-jsx (compile target: flue). Do not edit.
// Plain .ts on purpose: flue's discoverModules excludes .tsx — a discovered
// .ts entry importing the .tsx component is the sanctioned pattern.
//
// Static instructions below are the component's <prompt> rendered at the
// resting state. Live context (incidents etc.) is dynamic — re-render the
// component per turn and pass renderPrompt(...) as the task context instead
// of baking it here.

import { defineAgent } from "@flue/runtime";
import { evaluateTree } from "./runtime/compile/evaluate.ts";
import { collectInfra } from "./runtime/tree.ts";
import { createStore, withOutputs } from "./runtime/store.ts";
import { UptimeAgent } from "../agents/uptime-agent.tsx";
import { investigatorProfile } from "./investigator.flue.ts";


// State + props derived structurally from the component spec (no state-type
// string, no per-emit propsJson): the spec is the single analyzed source.
type State = typeof UptimeAgent.spec.initialState & Record<string, unknown>;
const PROPS = {"sites":["https://a.example","https://b.example","https://c.example"]};

// defineAgent's initializer returns an AgentRuntimeConfig (model/instructions/
// tools/subagents/…). No `name` field — flue derives the agent name from the
// module/route, not the config object.
export default defineAgent(() => ({
  model: "openrouter/google/gemini-3.1-flash-lite-preview",
  instructions: "[system] Uptime agent for 3 sites. Open a ticket per incident; skip if one exists.\nhistory: https://a.example routine checks nominal, p95 latency stable.\nhistory: https://b.example routine checks nominal, p95 latency stable.\nhistory: https://c.example routine checks nominal, p95 latency stable.",
  // Explicit subagent/capability roster for session.task(..., { agent }).
  subagents: [investigatorProfile],

  // No static tools: the component's <tool> is state-gated (e.g. page-oncall
  // only during an incident). Surface it per-turn via the harness rather than
  // as an always-on definition tool. flue has no sensor primitive either —
  // poll sensors belong in a flue workflow (cron) that calls session.prompt
  // with fresh observations.
}));

/**
 * Dynamic residue (subagent:investigate:https://b.example, tool:page-oncall): flue's runtime has no state→render
 * loop, so state-gated children compile to a spawn plan the orchestrating
 * workflow calls after each state change. Stable ids come from `name` —
 * "the #1 production bug" per flue's render-prop plan, solved by contract.
 * Child props are spread into the boundary config, so the delegated task input
 * is config minus the reserved `kind` discriminator.
 */
export function spawnPlan(state: State) {
  const store = createStore<State>(state);
  // Continuation grandchildren expand from the reserved __outputs slot: once a
  // child's emit has landed in state.__outputs, this plan fans out the boundary's
  // render-prop children (the workflow round that folded the emit calls spawnPlan
  // again). `emits` marks a boundary whose delegate resolves a structured output.
  const outputs = (state as { __outputs?: Record<string, unknown> }).__outputs ?? {};
  // .spec.impl renders the agent's OWN tree; a bare component call would be a
  // subagent boundary (parent composition), collapsing the whole plan to one.
  const desired = withOutputs({ outputs, setOutput: () => {} }, () =>
    evaluateTree(UptimeAgent.spec.impl({ ...PROPS, store, emit: () => {} }))
  ).flatMap((root) => collectInfra(root));
  return desired
    .filter((r) => r.kind === "subagent")
    .map((r) => {
      const { kind, ...input } = r.config;
      return {
        stableId: r.name,
        agent: String(kind),
        input,
        emits: r.bindings?.__emit?.kind === "continuation",
        bindings: r.bindings ?? {},
        resultBinding: Object.entries(r.bindings ?? {}).find(([, b]) => b.kind === "result")?.[0] ?? null,
        target: r.target ?? null,
      };
    });
}
